### ISSUE TITLE
RFC: Removing iobot

### ISSUE THREAD

**Issue by treznick** [newhavenio/playbooks#3]
Iobot, our trusty hubot robot in the newhavenio slack has two dependencies that are EOL. It also adds a lot of noise and a little of value to our slack.

We propose spinning down iobot within two weeks of this posting.

Here are the details:

Problems:

1. on August 8th, 2022 our redis provider, redistogo, is going away. 
2. On September, 20, 2022 the slack rtm.start and rtm.connect api's will start a deprecation of verbose behavior. See https://api.slack.com/changelog/2021-10-rtm-start-to-stop for more details. As mentioned [here](https://github.com/slackapi/hubot-slack/issues/630), slack has no plans to support this for the hubot slack adapter. 
3. iobot has had very little development. The last deployment (and feature iteration) was on Apr 21, 2021, and it was to allow feature flagging of noisier response behaviors.

What do we plan to do:

1. Before redistogo goes offline,  I'll fork the redis store into heroku hobby tier redis. As the bot runs on heroku, this means that cutting over to the fork is easy peasy. This gives us an escape hatch if we want to keep iobot alive.
2. If someone wants to migrate our hubot over to boltjs (following this guide: https://slack.dev/bolt-js/tutorial/hubot-migration), and can commit to both supporting the bot and developing it, we are happy to explore that option.

For now though, we're planning on spinning it down. Please comment here if you would like to propose alternatives.

**Comment by Christopher-Hayes** [comment]
May iobot RIP in peace. I agree there wasn't a ton of value the bot added to conversation.

It was a fun bot to have. If there's another bot or different way of hosting iobot where starting from scratch would be super easy to set up and little effort to maintain, I'd be willing support that effort. In it's current form, it doesn't seem worth the effort.

The bees are dead, long live the bees.

**Comment by treznick** [comment]
I'm forking the redis. I've started with our staging hubot in our staging slack:

1. fork redistogo into hobby-dev heroku redis

```
heroku addons:create heroku-redis:hobby-dev --fork $(heroku config:get REDISTOGO_URL -a newhavenio-bot-staging) -a newhavenio-bot-staging
```

2. shasum redistogo redis

```
redis-cli -u $(heroku config:get REDISTOGO_URL -a newhavenio-bot-staging) get hubot:storage | shasum
0e3cecf3e7c95fbf6f514679bf8cc5362434a650  -
```

3. once the redis is forked, check the checksum:
```
redis-cli -u $(heroku config:get REDIS_URL -a newhavenio-bot-staging) get hubot:storage | shasum
0e3cecf3e7c95fbf6f514679bf8cc5362434a650  -
```

4. destroy the old redis
```
heroku addons:destroy REDISTOGO_URL  -a newhavenio-bot-staging --confirm newhavenio-bot-staging
```

5. confirm using a get set
<img width="332" alt="Screen Shot 2022-07-26 at 8 38 56 PM" src="https://user-images.githubusercontent.com/618499/181135775-17374409-8e58-4677-9a99-c7d673b6312a.png">

**Comment by treznick** [comment]
and now prod

1. maintenance mode:
```
heroku maintenance:on -a newhavenio-bot
```

2. scale down:
```
heroku ps -a newhavenio-bot
web.1: up 2022/07/26 19:19:39 -0400 (~ 1h ago)

heroku ps:scale web=0 -a newhavenio-bot
```

3. shasum redistogo redis

```
redis-cli -u $(heroku config:get REDISTOGO_URL -a newhavenio-bot) get hubot:storage | shasum
```

4. once the redis is forked, check the checksum:
```
redis-cli -u $(heroku config:get REDISTOGO_URL -a newhavenio-bot) get hubot:storage | shasum
4430f6d5e8f014b474858d0038bf176790e9b325  -
redis-cli -u $(heroku config:get REDIS_URL -a newhavenio-bot) get hubot:storage | shasum
4430f6d5e8f014b474858d0038bf176790e9b325  -

```

*NB*: we cannot attach a redistogo database to multiple apps so we cannot make a rollback "app" to hold the db. We also cannot attach the redistogo multiple times so we can't modify the config var. the hubot redis brain will load databases by checking for a redistogo url first because reasons, so we cannot actually test that this works without destroying the addon wtaf.

6. yolo
```
heroku addons:destroy REDISTOGO_URL  -a newhavenio-bot --confirm newhavenio-bot
```

7. check with [run local](https://github.com/uhoh-itsmaciek/heroku-run-localjs)
```
heroku plugins:install heroku-run-localjs
heroku run:local bin/hubot -a newhavenio-bot
iobot> @iobot top 10
iobot> ▇▅▅▃▃▁▁▁▁▁
1. lourinaldi : 5
2. zmorek : 4
3. bsutt123 : 4
4. http://stronglifts.com : 3
5. treznick : 3
6. iobot @justingill : 2
7. iobot : 2
8. mzagaja : 2
9. not really sure if you're even an active c : 2
10. iobot arthur : 2
```

**Comment by treznick** [comment]
Heroku will be deprecating hobby tier redis. I’m going to remove iobot

**Comment by treznick** [comment]
I have spun down the dynos.
